# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:
  php:
    image: ${STACK_PHP_IMAGE}
    build:
      dockerfile: Dockerfile
      context: .
      #args:
      #  - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    ports:
      - 21080:80
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      - PHP_USER_ID=1000
      #- GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      # For usage with https://github.com/jwilder/nginx-proxy
      # - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - ./src/modules:/app/src/modules
      # Develop with additional packages
      #- ~/.composer/cache:/root/.composer/cache
      #- ./composer.json:/app/composer.json
      #- ./composer.lock:/app/composer.lock
      # Debug
      #- ./src/app.env:/app/src/app.env
      #- ./web/assets:/app/web/assets
      #- ./vendor:/app/vendor
      #- ./runtime:/app/runtime
  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
