# Local stack overrides
#
# Variables are populated with values from `.env`
#
version: '2.2'
services:

  php:
    volumes:
      # Debug
      #- ./_host-volume/assets:/app/web/assets
      - ./_host-volume/runtime:/app/runtime