# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2.1'
services:

  php:
    build: .
    ports:
      - '21080:80'
    depends_on:
      - db
      - redis
      - mailcatcher
    environment:
      # Development ONLY settings
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      - GITHUB_API_TOKEN
      - ENV_LOCAL_FILE=../project/config/local.env
      - APP_MAILER_USE_FILE_TRANSPORT=1

    volumes:
      # Application source-code
      - ./project/:/app/project:cached
      # Vendor source-code
      - ./vendor:/app/vendor:delegated
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached

  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '21090:3306'

  mailcatcher:
    image: nisenabe/mailcatcher
    ports:
      - '1080'